### PR TITLE
Created Testflow Details Page

### PR DESCRIPTION
**Pull request by MrSupiri**
### At the start of the test

Details page as of flowtest creation

### When the test is completed

Details page after flowtest is complete

Issues: #34

### CODE REVIEW

**Comment by paynejacob** [comment]
We can drop the yaml section.  If a use wants to view it they can use `kubectl describe flowtest`.  Can we also add some clearer messaging around the pass fail section.  The color is a good indicator but we should also have Text that says PASS / FAIL.  Colors should always be an aid not the only indicator.  Also how does this display if you had many match / filter statements?  Some flows can get complex and contain 10+.

**Review by paynejacob — COMMENTED** [review]
We can drop the yaml section. If a use wants to view it they can use kubectl describe flowtest. Can we also add some clearer messaging around the pass fail section. The color is a good indicator but we should also have Text that says PASS / FAIL. Colors should always be an aid not the only indicator. Also how does this display if you had many match / filter statements? Some flows can get complex and contain 10+.

**Comment by MrSupiri** [comment]
Ok, I will add some sort of label to say, red ones are failing, green ones are ok. To display, I pull the original flow and iterate over the matches and filters by mapping them to `<pre></pre>` tag. So this should work for any number of match/filter statements

**Comment by MrSupiri** [comment]
I added 4 tooltips to give additional feedback to the user

Passing filter tooltip
image

Failing failter tooltip
image

**Comment by paynejacob** [comment]
@MrSupiri The indicator for the filters need to be more obvious.  You could put them in a well with a title of pass / fail or add a second column next to them with a pass fail but it needs to be persistent and obvious.  This is particularly important for users who are color blind.  With the tooltip solution they would need to hover every step and try to remember which one broke.

**Review by paynejacob — CHANGES_REQUESTED** [review]
@MrSupiri The indicator for the filters need to be more obvious. You could put them in a well with a title of pass / fail or add a second column next to them with a pass fail but it needs to be persistent and obvious. This is particularly important for users who are color blind. With the tooltip solution they would need to hover every step and try to remember which one broke.

**Comment by MrSupiri** [comment]
New UI

image

**Comment by MrSupiri** [comment]
image

**Review by paynejacob — APPROVED** [review]

**Pull request merged**
